PRIYESHSINGH24/DSA_SOLUTION_PLATFORM

Creative interface
Prototype of creative interface
=> Made a Creative interface

index.html, styles.css
Here is the footer section, please add some labels before merging the PR. 
Write now, logo is not there so it looks like default, after the logo will come then i will place this as well.
@PRIYESHSINGH24
=> Updating Footer Section of the Website

index.html
fixed issue #23 Add top scroll button . @PRIYESHSINGH24 add SWOC  labels .
Screenrecording :
https://github.com/user-attachments/assets/4b25f15e-1692-4b17-af04-e14aeac3327b
=> Fixed top scroll button

DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/SORTING TECHNIQUES/Bucketsort.c, DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/SORTING TECHNIQUES/Countingsort.c, DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/SORTING TECHNIQUES/Heapsort.c, DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/SORTING TECHNIQUES/Radixsort.c, DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/SORTING TECHNIQUES/Shellsort.c, index.html, script.js, styles.css
<h4 align="Center">I have added the Navbar with basic links</h4>
<h2 align="center"><a href="https://rawcdn.githack.com/NishantRana07/DSA_SOLUTION_PLATFORM/1390174d0dc595fbd14817a92fc5a62a7a42ad85/index.html">Live link</a></h2>
<hr>
<h3 align="center">Its Better than old one and have hover effect too</h3>
<hr>
<h3 align="center">Its responsive</h3>
<hr>
<h3 align="center">Its based on Hamburger Approach</h3>
=> Better Navbar with links Added

DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/SORTING TECHNIQUES/Bucketsort.c, DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/SORTING TECHNIQUES/Countingsort.c, DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/SORTING TECHNIQUES/Heapsort.c, DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/SORTING TECHNIQUES/Radixsort.c, DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/SORTING TECHNIQUES/Shellsort.c
- @PRIYESHSINGH24 Bro please add it with Medium or hard label
<hr>
<h3>Sorting techniques added</h3>
- Heap Sort <br>
- Radix Sort <br>
- Bucket Sort <br>
- Shell Sort <br>
- Bucket Sort <br>
=> Added 5 more sorting techniques

index.html, pages/code360bycn.html
This page have some issues, so i fix tem properly.
=> I fix some bugs.

DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/SEARCHING TECHNIQUES/ExponentialSearch.c, DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/SEARCHING TECHNIQUES/FibonacciSearch.c, DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/SEARCHING TECHNIQUES/JumpSearch.c, DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/SEARCHING TECHNIQUES/TernarySearch.c
<h3 align="Center">Please merge it with hard/intermediate Label</h3>
=> 4 Searching algorithms added

DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/GRAPH TRAVERSAL TECHNIQUES/CODE WITH HARRY (CODES)/Dijkstra'sAlgo.c, DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/GRAPH TRAVERSAL TECHNIQUES/CODE WITH HARRY (CODES)/PrimsAlgo.c, DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/GRAPH TRAVERSAL TECHNIQUES/CODE WITH HARRY (CODES)/RandomWalk.c, DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/GRAPH TRAVERSAL TECHNIQUES/CODE WITH HARRY (CODES)/TopologicalSort.c
<h3 align="center">Please merge with maximum points</h3>
=> 4 Graph Traversal techniques Added Bro

index.html, terms.html
Fixed terms and Services Page @PRIYESHSINGH24 Add SWOC levels To this PR 
Screenrecording :
https://github.com/user-attachments/assets/0721e8a4-effe-40f6-9c04-604add8a43c4
=> Add terms and Services to the website

Security.html, index.html
Fixed Security page @PRIYESHSINGH24 Add SWOC levels to this PR 
Screenrecording : 
https://github.com/user-attachments/assets/3ea33656-a19c-4b10-987d-c9ac7f12a105
=> Add Security page to website

pages/geeksforgeeks.html
like this?  @PRIYESHSINGH24 
https://github.com/user-attachments/assets/025da835-9491-4557-9aa9-ade300641535
=> add the question into the page in their respective platform

pages/leetcode.css, pages/leetcode.html, pages/leetcode.js
Issue no: #16 
I added leetcode fetching from https://leetcode-stats-api.herokuapp.com 
Here's the output
https://github.com/user-attachments/assets/52e6fbea-cc78-45c7-aed6-bfb2b15b33c3
=> Updated leetcode files

DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/SORTING TECHNIQUES/heapsort.c
closes : #41 
Heap Sort is a comparison-based sorting algorithm that uses a binary heap data structure. The process consists of two main steps:
Building a Max-Heap: The input array is rearranged into a max-heap, where each parent node is greater than or equal to its children.
Sorting: The root (largest element) of the heap is swapped with the last element, then the heap property is restored for the reduced heap. This is repeated until the array is fully sorted.
The program uses a heapify function to maintain the max-heap property during sorting, and the swap function to exchange elements. The overall time complexity is O(n log n), making it efficient for large datasets.
=> Added heapsort program in sorting techniques

DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/BINARY TREE/DFS Traversal for Binary Tree (Recursive).c
Add a program to find DFS traversal (Inorder, Preorder, Postorder) for binary tree.
Sovles issue #79
=> Create DFS Traversal for Binary Tree (Recursive).c

contact.html, index.html
Contact Page fixed @PRIYESHSINGH24 , Add SWOC labels to this PR 
Screenrecording :
https://github.com/user-attachments/assets/2fef7e95-3d2b-4243-b558-71f07894cbf5
=> Contact Us Page Fixed

pages/geekforgeek.css, pages/geeksforgeeks.html
I have fixed the form of the geekforgeek page where user can add new question solution.
Preview of it
=> fixed Form

contact.html, index.html, styles.css
I have fixed the navbar UI for the better looks and it now perfectly fit in the website theme and having cool animations.
=> fixed the navbar UI

package-lock.json, pages/codechef.html
Changed the heading and title of codechef
=> Changed the heading from leetcode problems to codechef problems

index.html, styles.css
@PRIYESHSINGH24 
#83 Fixed the descirbed issue 
pls merge and add suitable labels.
=> Fixed Issues in Landing Page 

index.html, styles.css
#82 Fixed the described issue 
@PRIYESHSINGH24 check and merge PR with suitable labels
=> Fixed Issues in Navbar

index.html, vanilla-tilt.js
Solved issue #92.
When user hover on a card the card also moves with the mouse arrow. I hope you like these changes and if you want any extra things to add then please tell me. Also, if everything's looks good then please merge this and give me a score 😄
=> Hover 3d effect on cards

Security.html, about.html, contact.html, contributors.html, index.html, privacy.html, terms.html
- Added a new **About Us page** to the application.
- Implemented responsiveness for various screen sizes.
- Integrated a **3D hover effect** for cards to enhance interactivity and user experience.
https://github.com/user-attachments/assets/5ca9f4fd-fb72-49d6-951c-d14d020fa101
1. Responsive layout across all devices.
2. Visually appealing card design with hover effects.
3. Matches the existing design language of the platform.
Hey @PRIYESHSINGH24, I hope that you like these changes and merge this PR if you have any doubts than feel free to ask. 😊
=> Added about us page

Algorithmic Strategies/Brute-Force.README.md, DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/SEARCHING TECHNIQUES/LargestElement.c
=> Algorithm to find largest element in an array

index.html, styles.css
I just make footer more attractive and add "Stay Updated" section.
=> Make Footer better

about.html, index.html
=> I fix some bug in footer section.

pages/code360bycn.css, pages/code360bycn.html, pages/codechef.css, pages/codechef.html, pages/leetcode.css, pages/leetcode.html
Fixes #105 
This PR addresses the current limitation of the platform where the "Add Question" feature is available only for one platform out of the four supported platforms: GeeksforGeeks, LeetCode, CodeChef, and Coding Ninjas' Coding 360. This inconsistency restricts users from leveraging the feature uniformly across all platforms.
=> Added Que-adding-form on every platform

contact.html, contributors.html
i solved the issue .
before 
after
=> UPDATE THE CONTACT PAGE

contributors.html
add navbar into contributor page.
=> ADD NAVBAR INTO CONTRIBUTOR PAGE

LeetCode/1. Two Sum.c, LeetCode/1108. Defanging an IP Address.c, LeetCode/1281. Subtract the Product and Sum of Digits of an Integer.c, LeetCode/1346. Check If N and Its Double Exist.c, LeetCode/136. Single Number.c
1 Two Sum
136 Single Number
1108 Defanging an IP Address
1281 Subtract the Product and Sum of Digits of an Integer
1346 Check If N and Its Double Exist
Solves issue #125
=> Added LeetCode solution for:

DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/tree_graph/BINARY TREE/Inorder Traversal on Binary Tree (Non recursive).c
Added Inorder Traversal on Binary Tree (Non recursive).c
=> Create Inorder Traversal on Binary Tree (Non recursive).c

Algorithmic Strategies/Dynamic Programing .README.md
=> Create Dynamic Programing .README.md

about.html
=> I make some major changes on "About us" page. 

Algorithmic Strategies/Branch-and-Bound  .README.md
=> Create Branch-and-Bound  .README.md

DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/tree_graph/BINARY TREE/Postorder Traversal on Binary Tree (Non recursive).c
I have added postorder traversal on Binary Tree
=> Create Postorder Traversal on Binary Tree (Non recursive).c

LeetCode/1400. Construct K Palindrome Strings.c, LeetCode/1408. String Matching in an Array.c, LeetCode/1455. Check If a Word Occurs As a Prefix of Any Word in a Sentence.c, LeetCode/1470. Shuffle the Array.c, LeetCode/1480. Running Sum of 1d Array.c
Added solution for there questions:
1400 Construct K Palindrome Strings
1408 String Matching in an Array
1455 Check If a Word Occurs As a Prefix of Any Word in a Sentence
1470 Shuffle the Array
1480. Running Sum of 1d Array
Solves issue #135
=> Added more LeetCode solutions

contact.html, styles.css
=> Make some changes on "Contact us" page. Hope you like.

DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/BINARY TREE/FLoyd Warshall Algorithm.c
=> Create FLoyd Warshall Algorithm.c

DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/BINARY TREE/Bellman Ford Algorthim.c
=> Create Bellman Ford Algorthim.c

DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/Dijkstra's Algorithm in BINARY TREE .c
=> Create Dijkstra's Algorithm in BINARY TREE .c

Algorithmic Strategies/LCS Problem.README.md
=> Create LCS Problem.README.md

DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/tree_graph/BINARY TREE/Preorder Traversal on Binary Tree (Non recursive).c
Added Preorder Traversal on Binary Tree
=> Create Preorder Traversal on Binary Tree (Non recursive).c

about.html, contact.html, index.html, pages/code360bycn.css, pages/code360bycn.html, pages/code360bycn.js, pages/codechef.css, pages/codechef.html, pages/codechef.js, pages/geekforgeek.css, pages/geekforgeek.js, pages/geeksforgeeks.html, pages/leetcode.css, pages/leetcode.html, pages/leetcode.js, script.js, styles.css
@PRIYESHSINGH24 added feature described in the issue #154 
review and merge PR and give PTS accordingly
=> Added Cursor Animation in whole Website

pages/geekforgeek.js, pages/geeksforgeeks.html
ascll Function. SEE-
Before-
After-
=> Added one more question on geeksforgeeks page

about.html, script.js, styles.css
@PRIYESHSINGH24  resolved issue described in #155 
review , merge and give pts
=> Fixed Issues in Landing Page and Footer of About us

DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/tree_graph/BINARY TREE/Inorder Traversal on Binary Tree (Recursive).c
Added Inorder Traversal on Binary Tree (Recursive)
=> Create Inorder Traversal on Binary Tree (Recursive).c

pages/code360bycn.css, pages/code360bycn.html, pages/codechef.css, pages/codechef.html, pages/geekforgeek.css, pages/geeksforgeeks.html
=> Added check-progress on every platform

Geeks For Geeks/Alternates in an Array.py, Geeks For Geeks/Array Duplicates.py, Geeks For Geeks/Array Search.py, Geeks For Geeks/Array Subset.py, Geeks For Geeks/At least two greater elements.py, Geeks For Geeks/Balanced Array.py, Geeks For Geeks/Check Equal Arrays.py
=> Added GFG solutions

Security.html, about.html, contact.html, index.html, privacy.html, terms.html
Changed the old twitter icon with x-twitter icon from web pages.
=> Updated Twitter icon

pages/codechef2.html
fixed this issues @PRIYESHSINGH24 Add SWOC levels to this PR
Screenrecording 
https://github.com/user-attachments/assets/6fd08724-eac3-45d5-a5c7-ca91593325a3
=> fixed add the question into the page in their respective platform

DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/tree_graph/BINARY TREE/Postorder Traversal on Binary Tree (Recursive).c
Added Postorder Traversal on Binary Tree (Recursive)
=> Create Postorder Traversal on Binary Tree (Recursive).c

Security.html, about.html, contact.html, contributors.html, index.html, privacy.html, terms.html
Footer Copyright Year is Dynamic now .
Closes : #27
=> 🛠️Fix : Footer Copyright Year is Dynamic

Login1.html, Signup2.html, index.html
Fixed this Issue Add SWOC levels to this PR 
Screenrecording 
https://github.com/user-attachments/assets/dfb075cb-6cfd-4a3b-848f-55365f5e27b3
=> Add login and sign up page

DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/tree_graph/BINARY TREE/Preorder Traversal on Binary Tree (Recursive).c
@PRIYESHSINGH24 
Review this please.
Added Preorder Traversal on Binary Tree (Recursive)
=> Create Preorder Traversal on Binary Tree (Recursive).c

login.html, signup.html
I have added a well-designed sign up page. 
Kindly merge this pull request.
=> Added Sign up page

.hintrc, index.html
#152 Resolved issue which is described 
@PRIYESHSINGH24 merge , review and give pts for this PR
=> Fixed Issues in Footer

DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/tree_graph/GRAPH TECHNIQUES/Creating a Graph and Displaying.cpp
Added code for Creating a Graph and Displaying
=> Create Creating a Graph and Displaying.cpp

index.html, pages/codechef.css, pages/codechef3.html
fixed this issues @PRIYESHSINGH24 Add SWOC levels to this PR 
Screenrecording 
https://github.com/user-attachments/assets/516f3ee3-a993-4c05-ad14-d91b6f304048
=> add the question into the page in their respective platform .

contributors.html
fixed this Issues @PRIYESHSINGH24 
https://github.com/user-attachments/assets/2ea9a241-0d1a-4abd-921b-9d9096d2466d
=> improve Contributor page

Geeks For Geeks/Count Odd Even.py, Geeks For Geeks/Count of smaller elements.py, Geeks For Geeks/Display longest name.py, Geeks For Geeks/Fighting the darkness.py, Geeks For Geeks/Find distinct elements.py, Geeks For Geeks/Find element at a given Index.py, Geeks For Geeks/Game with nos.py
Added solution for:
Solves #188
=> Added more GFG solutions

DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/tree_graph/BINARY TREE/Level Order Traversal (BFS) on Binary Tree.cpp
Added Level Order Traversal (BFS) on Binary Tree
=> Create Level Order Traversal (BFS) on Binary Tree.cpp

pages/code360bycn.css, pages/codechef.css, pages/geekforgeek.css, pages/leetcode.css
`Fixes` #104 
`Before`
`After`
=> Enhance Question Display

Login1.html, Signup2.html, login.html, signup.html
#209 Resolved issue described in the issue
@PRIYESHSINGH24 review , merge and give pts
=> Fixed Issues in Login and Signup Pages

DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/Threaded Binary Tree/TBT Creation.cpp
Added Threaded binary tree creation
=> Create TBT Creation.cpp

about.html, about.js, index.html, script.js, styles.css
#231 added the feature described in the issue.
@PRIYESHSINGH24 review,merge and give pts.
=> Added Animation in About Page

script.js, styles.css
#232 Resolved Issue described .
@PRIYESHSINGH24 review, merge and give pts.
=> Fixed Issues in Landing page

index.html, styles.css
https://github.com/user-attachments/assets/9524d8d6-b267-4cc0-bafe-ff1646e5d43d
=> Enhanced Platform buttons

index.html
This Pr is related to issue :
@PRIYESHSINGH24  Check it once , and add SWOC labels for the same. Thank you
=> Corrected the security page error

pages/geeksforgeeks.html, pages/leetcode.html, pages/leetcode.js
Hello @PRIYESHSINGH24 
I have added the functionality of fetching rank for the users on leetcode 
Now the users can seemlessly get all required data like rank easily
=> fetching leetcode rank

Geeks For Geeks/Count the Zeros.py, Geeks For Geeks/Ishaan Loves Chocolates.py, Geeks For Geeks/Largest Element in Array.py, Geeks For Geeks/Max and Min Product from 2 Arrays.py, Geeks For Geeks/Min and Max in Array.py, Geeks For Geeks/Minimum Sum of Absolute Differences of Pairs.py, Geeks For Geeks/Multiply Array.py, Geeks For Geeks/Multiply left and right array sum.py, Geeks For Geeks/Non Repeating Character.py, Geeks For Geeks/Palindrome Array.py
Solves issue #234 
Questions solved:
Count the Zeroes
Ishaan Loves Chocolates
Largest Element in array
Max and Min product from 2 arrays
Min and Max in array
Minimum Sum of Absolute Differences of Pairs
Multiply Array
Multiply left and right array sum
Non Repeating Character
Palindrome Array
=> Added new GFG solutions.

models/user.model.js, pages/geeksforgeeks.html, pages/leetcode.html, pages/leetcode.js
I have created the user model using mongoose for this project
=> user Model created 

DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/Threaded Binary Tree/Inorder Traversal on TBT.cpp
Added Inorder Traversal on TBT
=> Create Inorder Traversal on TBT.cpp

.vscode/c_cpp_properties.json, .vscode/launch.json, .vscode/settings.json, DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/Linked List/merging k sorted linked lists.c
Explanation:
mergeTwoLists Function: Recursively merges two sorted linked lists into one.
mergeKLists Function: Uses the divide-and-conquer approach to recursively merge k sorted linked lists. It splits the array of lists into two halves, merges each half, and then combines them.
Example Usage: Creates three sample linked lists and merges them using the mergeKLists function.
This approach ensures that the merging process is efficient, leveraging the divide-and-conquer strategy. The time complexity is 
O(Nlogk), where 
N is the total number of nodes and 
k is the number of linked lists.
=> Add merging k sorted linked lists Soln

terms.html
Fixed this issue @PRIYESHSINGH24 Add SWOC levels to this PR 
https://github.com/user-attachments/assets/617fb438-c48c-4acd-b82f-ccd281623e6a
=> Improve Terms and Service page

code360bycn.css, code360bycn.html, codechef.css, codechef3.html, geekforgeek.css, geeksforgeeks.html, hacker.css, hackerrank.html, index.html, leetcode.css, leetcode.html
Fixed @PRIYESHSINGH24  Add SWOC 
https://github.com/user-attachments/assets/8e0cc8dc-8bd4-4989-8812-3666c3c03e64
=> Add links in this  buttons

index.html, styles.css
I have fixed the difference in size of the cards and made some small changes to make it look better
Issue number #241 
Before changes
After changes
=> fixed size difference of cards

DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/Linked List/Deletion at End.cpp
Added Deletion at End for Linked List
=> Create Deletion at End.cpp

Login1.html, Security.html, contributors.html, index.html, login.html, pages/Login.css, pages/Login.html, platform.html, privacy.html, signup.html, terms.html, work.html
update navbar for all footer redirect links like blog,work, privacy,security,terms ,login ,sign up .
please review it and merge into main make label swoc . and give points.
=> add navbar for all footer redirect ,login,sign up

Algorithmic Strategies/DivideandConquer.README.MD, DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/DIVIDE AND CONQUER TECHNIQUES/binarysearch.c, DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/DIVIDE AND CONQUER TECHNIQUES/maximum.c, DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/DIVIDE AND CONQUER TECHNIQUES/mergesort.c, DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/DIVIDE AND CONQUER TECHNIQUES/quicksort.c
Added DIVIDE AND CONQUER TECHNIQUES 
In this Added, DivideandConquer README.MD
Added 1. Quicksort
2. Merge Sort
3. binarysearch 
4. Maximim and Minimum Array 
Add SWOC labels to this PR , @PRIYESHSINGH24
=> Add Divide and Conquer Techniques

platform.html
Fixed @PRIYESHSINGH24 Add SWOC levels to This PR.
https://github.com/user-attachments/assets/2395c30a-a3e0-4341-9283-9b9fe430d854
=> Improve Platform Footer

DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/Linked List/Deletion at Head.cpp
Added Deletion at Head for linked list
=> Create Deletion at Head.cpp

DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/Linked List/Reverse Linked List.c
=> Create Reverse Linked List.c

DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/GRAPH TRAVERSAL TECHNIQUES/CODE WITH HARRY (CODES)/Kruskal's Algorithm.c
=> Create Kruskal's Algorithm.c

DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/GRAPH TRAVERSAL TECHNIQUES/CODE WITH HARRY (CODES)/Floyd-Warshall Algorithm.c
=> Create Floyd-Warshall Algorithm.c

DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/GRAPH TRAVERSAL TECHNIQUES/CODE WITH HARRY (CODES)/Bellman-Ford Algorithm.c
=> Create Bellman-Ford Algorithm.c

DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/Linked List/Deletion By Value.c
=> Create Deletion By Value.c

DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/Linked List/Length of a Linked List.c
=> Create Length of a Linked List.c

Algorithmic Strategies/Two Sum Problem  .README.md
=> Create Two Sum Problem  .README.md

Algorithmic Strategies/3 Sum Problem  .README.md
=> Create 3 Sum Problem  .README.md

Algorithmic Strategies/Prim's Algorithm .README.md, pages/SignUp.html
=> Added Prims Algorithm in C

pages/SignUp.html
=> Signup.html have bug (CSS file not applied)

Algorithmic Strategies/Knapsack Problem  .README.md
=> Create Knapsack Problem  .README.md

Algorithmic Strategies/Traveling Salesman Problem (TSP)  .README.md
=> Create Traveling Salesman Problem (TSP)  .README.md

contact.html, styles.css
Fixed @PRIYESHSINGH24 Add SWOC level to this PR 
https://github.com/user-attachments/assets/ae68d2be-f00b-43e0-b981-d022c33a2f27
=> improve header and footer in contact us page

pages/code360bycn.css, pages/code360bycn.html, pages/code360bycn.js, pages/codechef.css, pages/codechef.html, pages/codechef.js, pages/codeforces.html, pages/geekforgeek.css, pages/geekforgeek.js, pages/geeksforgeeks.html, pages/hacker.css, pages/hacker.js, pages/hackerrank.html, pages/leetcode.css, pages/leetcode.html, pages/leetcode.js
`Fixes` #257 
**Issue Addressed**
This PR resolves the issue where the "Check Your Progress" section, displayed alongside the problems and solutions, impacts the overall balance and visual appeal of the page.
**Proposed Solution**
Replaced the "Check Your Progress" section with a button labeled "Check Progress".
Implemented a pop-up card interface that appears when the button is clicked.
The pop-up card contains a well-structured progress tracker, improving visual focus and user interaction.
**Before**
**After**
=> Replace "Check-Progress" section with a button-triggered pop-up card

Geeks For Geeks/Subarray Sum Equals K.py
Subarray Sum Equals K
Given an array of integers and an integer k, find the total number of continuous subarrays whose sum equals k.
Example: Input: nums = [1, 1, 1], k = 2, Output: 2.
=> Create Subarray Sum Equals K.py

Geeks For Geeks/Sorted Array.py
Find the Minimum in Rotated Sorted Array
Find the minimum element in a rotated sorted array without duplicates.
Example: Input: [3, 4, 5, 1, 2], Output: 1.
@PRIYESHSINGH24  Add SWOC levels to this PR
=> Create Sorted Array.py

Geeks For Geeks/Array.py
.Count Inversions in an Array
Count the number of inversions (i.e., pairs (i, j) where i < j and nums [i] > nums [j]) in the array.
=> Add Arrays questions

DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/DIVIDE AND CONQUER TECHNIQUES/Kthlargest.c, DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/DIVIDE AND CONQUER TECHNIQUES/countinversion.c, DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/DIVIDE AND CONQUER TECHNIQUES/majorityelement.c, DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/DIVIDE AND CONQUER TECHNIQUES/points.c
Added Intermediate Problems to the DIVIDE AND CONQUER TECHNIQUE ,
Add SWOC Labels to this PR 
Added Questions : 
1.  Count the number of inversions in an array using merge sort logic.
2.  Closest Pair of Points: Find the closest pair of points in a 2D plane.
3. Majority Element: Find the majority element in an array using divide and conquer.
4. Kth Largest/Smallest Element: Find the kth largest or smallest element in an array.
=> Intermediate Problems added to Divide and Conquer

about.html, contact.html
i have fixed navbar links redirection issue 
issue no #303 
<h1>Before changes</h1>
https://github.com/user-attachments/assets/39d2dd7e-8610-469c-bb25-69c871286042
<h1>After changes</h1>
https://github.com/user-attachments/assets/a62453bb-6290-4d93-98af-11383952ac4c
=> Fixed links redirection issue

about.html, contact.html
Issue no. #274 
Before Changes:
After Changes:
<h3>I have also fixed few other issues like, social-links placement and navbar responsiveness.
=> Fixed Contact page issues 

DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/Threaded Binary Tree/Preorder Recursive Traversal.cpp
Added Preorder Recursive Traversal
=> Create Preorder Recursive Traversal.cpp

LeetCode/46. Permuatations.java, LeetCode/51. N-Queens.java, LeetCode/523. Continuous Subarray Sum.java
#304 
46.Permutations
51.N-Queens
523.Continuous Subarray Sum
Language: JAVA
=> Added LeetCode solutions

DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/Linked List/DoublyLinkedList/Creation.cpp
This pull request adds the implementation of a Doubly Linked List (DLL) in C++. The features include the creation of the doubly linked list and displaying its elements in order.
Hey @PRIYESHSINGH24, please merge this PR under SWOC.
=> Doubly LinkedList creation

pages/Login.html, pages/SignUp.html
=> Fix a bug on SignUp.html page

Geeks For Geeks/Sorting problems/Quick sort.py
Here is a long and detailed implementation of the Quick Sort algorithm with step-by-step explanations, additional logic, and verbose outputs for understanding each step of the sorting process.
Quick Sort.py
=> Add  Quick Sort Problem

Geeks For Geeks/Sorting problems/Bubble Sort.py, Geeks For Geeks/Sorting problems/Insertion Sort.py, Geeks For Geeks/Sorting problems/Merge Sort.py, Geeks For Geeks/Sorting problems/Selection Sort.py
Add Sorting problems 
Bubble Sort.py
Selection Sort.py
Insertion Sort.py
Merge Sort.py
=> Add Sorting problems

Geeks For Geeks/Breadth-First Search (BFS).py
create a Breadth-First Search (BFS) problem
Breadth-First Search (BFS).py
=> Breadth-First Search (BFS) problem

Geeks For Geeks/Maximum Subarray Sum (Kadane's Algorithm).py
Maximum Subarray Sum (Kadane’s Algorithm - Solution).py
@PRIYESHSINGH24 Add SWOC level to this PR
=> Create Maximum Subarray Sum (Kadane’s Algorithm -  Solution)

Geeks For Geeks/Knapsack Problem (0/1 Knapsack).py, Geeks For Geeks/Knapsack Problem (0/Coin Change Problem.py
Knapsack Problem (0/1 Knapsack).py
Coin Change Problem.py
=> Add GFG solutions

Hacker Rank Solutions/Fibonacci Numbers (DP Approach).py, Hacker Rank Solutions/Longest Increasing Subsequence.py
Dynamic Programming problems for  HackerRank solutions 
Fibonacci Numbers (DP Approach).py
Longest Increasing Subsequence
@PRIYESHSINGH24  Add SWOC levels to this PR
=> Add Hacker rank solutions

DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/Stack/Building Stack.c
=> Create Building Stack.c

LeetCode/39. Combination Sum.java, LeetCode/40. Combination Sum II.java
#331 
39. Combination Sum
40. Combination Sum II 
Language: JAVA
=> Adding LeetCode Solutions

DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/doublyLinkedList.c
@PRIYESHSINGH24, create doubly linked list FIX #255
Insertion at beginning,end and k th position and deletion
=> create doubly linked list FIX #255

DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/GRAPH TRAVERSAL TECHNIQUES/CODE WITH HARRY (CODES)/Kosarajus's Algorithm.c
Kosarajus algo added #321 solved
=> kosaraju algo added

about.html, styles.css
Fixed @PRIYESHSINGH24  Add SWOC levels to this PR 
https://github.com/user-attachments/assets/3d239e13-f0f8-4572-8faf-5dfd16452f77
=> improve header and footer in about us .

codeforce/K-th Smallest Element in BST.java
Problem:
K-th Smallest Element in BST
-Codeforces Problem: K-th Smallest Element in Binary Search Tree (BST ) (Codeforces 662B)
-Topic: Binary Search Tree, In-order Traversal
Problem Description:
-Given a binary search tree (BST), find the k-th smallest element in the tree.
Solution Approach:
-The in-order traversal of a BST gives elements in sorted order.
-By performing an in-order traversal, you can efficiently find the k-th smallest element.
=>  K-th Smallest Element in Binary Search Tree (BST).java

codeforce/Segment Tree.java
Segment Tree
Problem: Maximum Subarray Sum (Codeforces 1198C)
Topic: Segment Tree, Dynamic Programming
Explanation:
Input:
- n: Number of elements in the array.
- arr[]: Array of integers.
- q: Number of queries.
- Each query consists of two integers l and r, specifying the range [l, r].
Segment Tree Implementation:
-Build Phase:
The segment tree is built recursively. Each node contains the maximum value of its range.
Time complexity: 
𝑂(𝑛).
Query Phase:
To find the maximum in a range [l, r], recursively check left and right children and combine their results.
Time complexity per query: 
𝑂(log𝑛).
Algorithm Steps:
- Parse input and construct the segment tree with the array.
- Process each query to find the maximum value in the specified range [l, r] using the query function.
- Output the …
=> Maximum Subarray Sum (Codeforces 1198C)

codeforce/Dynamic Programming Greedy.java
Dynamic Programming
Problem: Frog Jump (Codeforces 1407B)
Topic: DP, Greedy
Explanation:
Input:
- [t:] Number of test cases.
For each test case, [n:] Number of elements in the array and [a]: The array.
Approach:
-The goal is to form a permutation of the array such that the greatest GCDs are computed in order.
-Sort the array, start with the largest number, and iteratively pick the number that gives the maximum GCD with the current GCD.
Algorithm:
-Start with the largest number in the array as the first element in the permutation.
-Use a greedy approach to maximize the GCD at each step.
-Track visited elements to avoid repetition.
Output:
-Print the reordered array for each test case.
This approach ensures an optimal solution using sorting and iterative GCD calculations. The complexity is …
=> Dynamic Programming Greedy.java

LeetCode/4. Median of Two Sorted Arrays.py
Added new leetcode solution
4. Median of Two Sorted Arrays
=> Create 4. Median of Two Sorted Arrays.py

LeetCode/205. Isomorphic Strings.java, LeetCode/3110. Score of a String.java
#363 
3110.Score of a String
205.Isomorphic Strings
Language: JAVA
=> adding leetcode questions

platform.html
`Fixes` #381 
**Before**
**After**
=> Fix: Ensure Footer Consistency Across Platform 

DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/DP/Minimum-Cost-to-Cut-Stick.cpp
Approach
Sort the cuts array: Add 0 (start of the stick) and n (end of the stick) to the array to define boundaries.
Dynamic Programming Table:
Define a DP table dp[i][j] where i and j represent indices in the sorted cuts array. This table stores the minimum cost of cutting the stick between positions cuts[i] and cuts[j].
=> Minimum Cost to Cut a Stick Problem Soln  Added

LeetCode/CodeForce Solutions/Regular Bracket Sequence.java
Balanced Brackets
- Problem: Regular Bracket Sequence (Codeforces 5C)
- Topic: Stacks, Strings  
Explanation:
Input: A string of parentheses.
Output: The length of the longest valid bracket sequence and the count of such sequences.
Approach:
Use a stack to track unmatched opening brackets.
Use a dynamic programming array (dp) to store the length of valid sequences ending at each index.
Update maxLength and count as longer sequences are found.
Add SWOC level to this PR @PRIYESHSINGH24
=> Create Regular Bracket Sequence.java

DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/BINARY TREE/BST-or-Not.c, DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/BINARY TREE/subtree-of-another-tree.c
=> Added Binary tree problem

DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/BINARY TREE/subtree-of-another-tree.c
=> added DSA Question

LeetCode/132. Palindrome.c, LeetCode/1368. Path in a Grid.c, LeetCode/162. Alien Dictionary.c, LeetCode/312. Burst Balloons.c, LeetCode/630. Course Schedule III.c, LeetCode/97. Interleaving String.c
Fixed Advanced Solutions of Problems In Leetcode , Add SWOC Labels to this PR @PRIYESHSINGH24 
Added Questions : 
1. Palindrome Partitioning II
Problem: Partition a string such that every substring of the partition is a palindrome and return the minimum cuts needed.
2. Burst Balloons
Problem: Find the maximum coins you can collect by bursting balloons strategically.
3. Interleaving String
Problem: Check if a string is an interleaving of two other strings.
4. Alien Dictionary
Problem: Determine the order of characters in an alien language given a sorted dictionary.
5. Course Schedule III
Problem: Find the maximum number of courses that can be taken based on given schedules.
6. Minimum Cost to Make at Least One Valid Path in a Grid
Problem: Find the minimum cost to modify a grid such that …
=> Advanced Problems in Leetcode

Algorithmic Strategies/Hashing Technique.README.MD, DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/Hashing Techniques/Freq.java, DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/Hashing Techniques/Repele.java, DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/Hashing Techniques/Twoarray.java
added HASHING TECHNIQUE , Add SWOC Labels to this PR @PRIYESHSINGH24 
README.MD
Find the First Repeating Element
Count Frequencies of Elements
Check if Two Arrays Are Equal
=> HASHING TECNIQUE

index.html
I have fixed the contact us link in the footer as other links are now working so i have added corrected path for contact us.
=> Fixed link in footer of contact us

DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/DIVIDE AND CONQUER TECHNIQUES/Challenge Problems/Merge.c, DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/DIVIDE AND CONQUER TECHNIQUES/Challenge Problems/Minarray.c, DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/DIVIDE AND CONQUER TECHNIQUES/Challenge Problems/hull.c, DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/DIVIDE AND CONQUER TECHNIQUES/Challenge Problems/infinite.c, DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/DIVIDE AND CONQUER TECHNIQUES/Challenge Problems/optimal.c
Added Challenge Problems to Divide and Conquer Technique , Add SWOC Labels to this PR @PRIYESHSINGH24 
Questions Added : 
Divide Array into Two with Minimum Difference: Partition an array into two subsets with minimal difference in sums.
Minimum Cost to Merge Files: Given sizes of files, find the minimum cost to merge them.
Optimal Binary Search Tree: Construct a binary search tree with minimal search cost given probabilities of elements.
Convex Hull Problem: Find the convex hull of a set of points using divide and conquer.
Find Element in Infinite Sorted Array: Search for an element in an infinite sorted array efficiently.
=> Challenge Problems Divide&Conquer

DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/DIVIDE AND CONQUER TECHNIQUES/Array2.c, DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/DIVIDE AND CONQUER TECHNIQUES/Rotate.c, DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/DIVIDE AND CONQUER TECHNIQUES/occurence.c
Added Advanced problems to Divide and Conquer Techniques , Add SWOC Labels to this PR @PRIYESHSINGH24 
Median of Two Sorted Arrays: Find the median of two sorted arrays.
Majority Element: Find the majority element in an array using divide and conquer.
Divide Array into Two with Minimum Difference: Partition an array into two subsets with minimal difference in sums.
=> Advanced Problems of Divide Conquer

LeetCode/10. Regular Expression Matching.py
Added 10. Regular Expression Matching LeetCode Difficulty: Hard
=> Create 10. Regular Expression Matching.py

DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/DIVIDE AND CONQUER TECHNIQUES/maxsub.c, DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/DIVIDE AND CONQUER TECHNIQUES/skyline.c, DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/DIVIDE AND CONQUER TECHNIQUES/strassens.c
Added hard Levels Problems Of Divide and Conquer , Add SWOC Labels to this PR @PRIYESHSINGH24 
Maximum Subarray Sum (Kadane’s with Divide and Conquer).
Find the maximum sum of a contiguous subarray.
Skyline Problem: Merge overlapping buildings represented as ranges to create a city skyline.
=> Add Hard Level Problems Divide and Conquer

LeetCode/753. Cracking the safe.c++, LeetCode/765. couple holding hands.cpp
leetcode 753 and 765 added (graph hard problems) solutions #439 solved
=> leetcode graph hard problem added

DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/PRIORITY QUEUE/leetcode 502. IPO.c++, DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/PRIORITY QUEUE/leetcode-480. Sliding window median.cpp, LeetCode/753. Cracking the safe.c++, LeetCode/765. couple holding hands.cpp
prority queue hard problems added to dsa solutions leetcode 480 and 502 #404 solved
=> priority queue hard problem added 

DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/PRIORITY QUEUE/leetcode 502. IPO.c++, DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/PRIORITY QUEUE/leetcode-480. Sliding window median.cpp, DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/TRIE/leetcode 356. Palindrome pairs .c++, DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/TRIE/leetcode 745. Prefix and Suffix Search.c++, LeetCode/753. Cracking the safe.c++, LeetCode/765. couple holding hands.cpp
leetcode 356 and 745 added (trie hard problems ) #412 solved
=> Trie hard problems added 

Coding Ninjas/Chocolate Pickup.cpp, Coding Ninjas/Ninja's Training.c++, DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/PRIORITY QUEUE/leetcode 502. IPO.c++, DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/PRIORITY QUEUE/leetcode-480. Sliding window median.cpp, DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/TRIE/leetcode 356. Palindrome pairs .c++, DSA SOLUTIONS (TILL TREE & BASIC GRAPH CONCEPTS)/TRIE/leetcode 745. Prefix and Suffix Search.c++, LeetCode/753. Cracking the safe.c++, LeetCode/765. couple holding hands.cpp
ninjas training and chocolate pickup problems added (coding ninjas) #426 solved
=> Coding ninjas hard problems added 

Algorithmic Strategies/Branch and Bound.README.md
Added  a new Algorithmic Strategies- Branch and Bound .
=> Create Branch and Bound file.

LeetCode/CodeForce Solutions/The number of positions.java
=> Create The number of positions.java

LeetCode/CodeForce Solutions/Shape Perimeter.java
=> Create Shape Perimeter.java

LeetCode/1402. Reducing Dishes.py
Added solution for 1402. Reducing Dishes LeetCode (Hard)
=> Create 1402. Reducing Dishes.py

LeetCode/3374. First Letter Capitalization II.sql
Added solution for 3374. First Letter Capitalization II LeetCode (Hard)
=> Create 3374. First Letter Capitalization II.sql

LeetCode/2392. Build a Matrix With Conditions.py
Added solution for 2392. Build a Matrix With Conditions LeetCode (Hard)
=> Create 2392. Build a Matrix With Conditions.py

LeetCode/1255. Maximum Score Words Formed by Letters.py
Added solution for 1255. Maximum Score Words Formed by Letters LeetCode (Hard)
=> Create 1255. Maximum Score Words Formed by Letters.py

LeetCode/980. Unique Paths III.py
Added solution for 980. Unique Paths III LeetCode (Hard)
=> Create 980. Unique Paths III.py

CODECHEF/College Admission.cpp
codechef college admission problem added #424  solved
=> codchef hard problem added

CODECHEF/College Admission.cpp, LeetCode/857.minimum cost to hire k workers.cpp, LeetCode/862. Shortest Subarray with Sum at Least K.cpp
leetcode 857 and 862 added to leetcode solutions (heap problems) #422  solved
=> heap hard problems added 

CODECHEF/College Admission.cpp, LeetCode/65.Valid Number.cpp, LeetCode/857.minimum cost to hire k workers.cpp, LeetCode/862. Shortest Subarray with Sum at Least K.cpp
add leetcode problem 65 valid number solution added #423  solved
=> Leetcode problem 65 solution 

Geeks For Geeks/3Sum Problem .java
3Sum Problem:
The goal is to find all unique triplets in an array that sum up to zero.
Two Pointers Technique is used to efficiently explore pairs (left, right) for each fixed element (nums[i]).
Steps:
-Sort the array to make it easier to apply two pointers.
-Use left and right pointers to explore possible triplets.
-Adjust left and right based on whether the sum is less than, equal to, or greater than zero.
-Skip duplicates to avoid repeating triplets.
Complexity:
-Time Complexity: O(n^2) (due to sorting and two-pointer traversal)
-Space Complexity: O(1) (constant space usage)
=> Create 3Sum Problem.java

STRING PRBLEMS/nonrepeating.c, STRING PRBLEMS/palindrome.c, STRING PRBLEMS/palindromicsubstring.c, STRING PRBLEMS/string.c, STRING PRBLEMS/windowsubstring.c
Hey @PRIYESHSINGH24  , please review and merge this PR under SWOC. Let me know if any changes or improvements are needed. 👍
Questions Added : 
1. Reverse a String
2. Check if a String is a Palindrome
3. Find the First Non-Repeating Character
4. Longest Palindromic Substring
5. Minimum Window Substring
=> Add questions of Strings

LeetCode/SudokuSolver.cpp, LeetCode/SudukoSolver.c, LeetCode/SudukoSolver.py
Fixes: #434 
**Languages**
1.C++
2.C
3.Python
@PRIYESHSINGH24 Please review and let me know if you need any changes
=> Add suduko solver problem

index.html, script.js, styles.css
Look-
https://github.com/user-attachments/assets/553da5e2-485b-4ab9-a8d6-66aade24971c
=> Update the Main Page

Geeks For Geeks/Trappingrainwater.c, Geeks For Geeks/TwoSortedArray.c, Geeks For Geeks/longestPalidromicSubstring.c
Hey @PRIYESHSINGH24  , please review and merge this PR under SWOC. Let me know if any changes or improvements are needed. 👍
Hard-Level Questions Added : 
Problem 1: Longest Palindromic Substring
Problem Statement: Given a string s, find the longest substring that is a palindrome.
Problem 2: Median of Two Sorted Arrays
Problem Statement: Given two sorted arrays nums1 and nums2 of size m and n respectively, return the median of the two sorted arrays.
Problem 3: Trapping Rain Water
Problem Statement: Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.
=> Hard Level Problems added to GFG

about.html
Issue #498
I Have fixed the footer of about us page 
Previously it was not styled properly was making conflicts with the two footers in the same page i have made it single and workable also fixed links of navbar in about page.
Here is the preview
Hope You Love It
=> Fixed Footer About us

styles.css
issue #495 
The issue is with the alignment of the image position in the hero section of the website .
I have removed unnecessary styles conflict and make it look best on the website.
Here is the preview
Hope You Love It.
=> Fixed Image Alignment

LeetCode/3161. Block Placement Queries.py
Added LeetCode Hard 3161. Block Placement Queries
=> Create 3161. Block Placement Queries.py

LeetCode/3343. Count Number of Balanced Permutations.py
Added LeetCode Hard 3343. Count Number of Balanced Permutations
=> Create 3343. Count Number of Balanced Permutations.py

LeetCode/3425. Longest Special Path.py
Added LeetCode Hard 3425. Longest Special Path
=> Create 3425. Longest Special Path.py

LeetCode/3333. Find the Original Typed String II.py
Added LeetCode Hard 3333. Find the Original Typed String II
=> Create 3333. Find the Original Typed String II.py

LeetCode/3321. Find X-Sum of All K-Long Subarrays II.py
Added LeetCode Hard 3321. Find X-Sum of All K-Long Subarrays II
=> Create 3321. Find X-Sum of All K-Long Subarrays II.py

LeetCode/3357. Minimize the Maximum Adjacent Element Difference.py
Added LeetCode Hard 3357. Minimize the Maximum Adjacent Element Difference
=> Create 3357. Minimize the Maximum Adjacent Element Difference.py

LeetCode/3260. Find the Largest Palindrome Divisible by K.py
Added LeetCode Hard 3260. Find the Largest Palindrome Divisible by K.
=> Create 3260. Find the Largest Palindrome Divisible by K.py

LeetCode/3256. Maximum Value Sum by Placing Three Rooks I.py
Added LeetCode Hard 3256. Maximum Value Sum by Placing Three Rooks I
=> Create 3256. Maximum Value Sum by Placing Three Rooks I.py

LeetCode/420. Strong Password Checker.py
Added LeetCode Hard 420. Strong Password Checker
=> Create 420. Strong Password Checker.py

LeetCode/3245. Alternating Groups III.py
Added LeetCode Hard 3245. Alternating Groups III
=> Create 3245. Alternating Groups III.py

LeetCode/3276. Select Cells in Grid With Maximum Score.py
Added LeetCode Hard 3276. Select Cells in Grid With Maximum Score
=> Create 3276. Select Cells in Grid With Maximum Score.py

LeetCode/3303. Find the Occurrence of First Almost Equal Substring.py
Added LeetCode Hard 3303. Find the Occurrence of First Almost Equal Substring
=> Create 3303. Find the Occurrence of First Almost Equal Substring.py

LeetCode/3266. Final Array State After K Multiplication Operations II.py
Added LeetCode Hard 3266. Final Array State After K Multiplication Operations II
=> Create 3266. Final Array State After K Multiplication Operations II.py

LeetCode/3348. Smallest Divisible Digit Product II.py
Added LeetCode Hard 3348. Smallest Divisible Digit Product II
=> Create 3348. Smallest Divisible Digit Product II.py

platform.html, privacy.html
=> fixed footer of Privacy policy page

Geeks For Geeks/Linear-search.c
=> Added Linear-search.c

LeetCode/Shortest Distance After Road Addition Queries I.java
=> Create Shortest Distance After Road Addition Queries I.java

Geeks For Geeks/Linear-search.c, Geeks For Geeks/Sum of max of all subarray.c
This is a hard level problems from GFG.
=> Added the sum of the maximum values of all subarrays in C

LeetCode/Defuse the Bomb.java
=> Create Defuse the Bomb.java

STRING PRBLEMS/Adding Spaces to a String.java
=> Create Adding Spaces to a String.java

LeetCode/Rotating the Box.java
=> Create Rotating the Box.java

LeetCode/Sliding Puzzle.java
=> Create Sliding Puzzle.java

about.html
**Fixes #514** 
🔹 **What's New?**  
I have successfully added a **scroll button** 🖱️ to the **About Page** of the project! This new feature enhances user navigation and provides a seamless experience by allowing users to quickly return to the top of the page.  
🔹 **Highlights**:  
✅ Smooth scroll animation for better aesthetics 🎥.  
✅ Responsive design for all devices 📱💻.  
✅ Intuitive placement to ensure easy accessibility 👌.  
🔹 **Why It Matters?**  
Adding a scroll button improves **usability** and keeps the page looking professional and user-friendly 🌟.  
Looking forward to hearing your thoughts! 💬 Your feedback means a lot 🙌.  
---
---
=> Enhanced the About Page with a Scroll Button 🚀💻

platform.html
https://github.com/user-attachments/assets/f1fb4994-0774-4145-85c1-98eec32b4d3a
#530 solved
=> platform page improved

codechef.css, codechef3.html, navbar.css, pages/code360bycn.css, pages/code360bycn.html, pages/codechef.css, pages/codechef.html, pages/codechef2.html, pages/codechef3.html, platform.html
"footer added in coding ninjas page and also update two pages codechef2 and codechf3 (html css js )"  
#540 solved
https://github.com/user-attachments/assets/61a9f2f5-9012-4718-833b-c33f08adfde3
=> "footer added in coding ninjas page and also update two pages codechef2 and codechf3 (html css js )"  

platform.html
=> double footer issue solved and new updated footer added

codechef.css, codechef3.html, navbar.css, pages/codechef.html, platform.html
=> navbar updated of codechef problem page 

codechef.css, codechef3.html, navbar.css, pages/codechef.html, platform.html
=> footer added to codechef problem page 

codechef.css, codechef3.html, navbar.css, pages/code360bycn.css, pages/code360bycn.html, pages/codechef.html, platform.html
#537 solved
improved header and navbar
=> Navbar added and ui improved of coding ninjas problem page 

LeetCode/3430. Maximum and Minimum Sums of at Most Size K Subarrays.py
Added LeetCode Hard 3430. Maximum and Minimum Sums of at Most Size K Subarrays
=> Create 3430. Maximum and Minimum Sums of at Most Size K Subarrays.py

LeetCode/3426. Manhattan Distances of All Arrangements of Pieces.py
Added LeetCode Hard 3426. Manhattan Distances of All Arrangements of Pieces
=> Create 3426. Manhattan Distances of All Arrangements of Pieces.py

LeetCode/3414. Maximum Score of Non-overlapping Intervals.py
Added LeetCode Hard 3414. Maximum Score of Non-overlapping Intervals
=> Create 3414. Maximum Score of Non-overlapping Intervals.py

LeetCode/3420. Count Non-Decreasing Subarrays After K Operations.c++
Added LeetCode Hard 3420. Count Non-Decreasing Subarrays After K Operations
=> Create 3420. Count Non-Decreasing Subarrays After K Operations.c++

LeetCode/3425. Longest Special Path.cpp
Added LeetCode Hard 3425. Longest Special Path
=> Create 3425. Longest Special Path.cpp

about.html, pages/geeksforgeeks.html, pages/hackerrank.html, privacy.html
Fixes: #568 
@PRIYESHSINGH24 please review
=> Improve footer in privacy policy

pages/geekforgeek.css, pages/geekforgeek.js, pages/geeksforgeeks.html
Fixes: #564 
https://github.com/user-attachments/assets/64575e3f-855d-464f-a19f-73b3a98f6527
@PRIYESHSINGH24 please review
=> Fix cards in GFG

pages/platform.html
@PRIYESHSINGH24
look-
https://github.com/user-attachments/assets/a6d349e1-2082-4149-8035-0bd7f8a0c48e
=> Organize the platform.html page.

pages/geekforgeek.css, pages/hacker.css, pages/hacker.js, pages/hackerrank.html
Fixes; #567 
@PRIYESHSINGH24 Please review
=> Improve cards alignment

pages/leetcode.css, pages/leetcode.html, pages/leetcode.js
Fixes: #566 
@PRIYESHSINGH24 please review
=> Fix cards in leetcode

pages/platform.html
issue #575 
I have fixed the links in the navbar of platform page.
Previously they are not working fine so i have fixed them and now they are redirecting to correct page.
=> Fixed Links In navbar

contact.css
Issue #576 
I Have fixed the cards in contact page
Previously it was not very much cool but now it is looking good
Here is the preview
Hope You Love It
=> Improved Contact UI

pages/hacker.js, pages/hackerrank.html
Hey @PRIYESHSINGH24 ,
Could you Please review and let me know if any further updates are needed and merge this PR under SWOC. 😊
Screenshots :
=> Add Question of Strings Reversal

index.html, testimonial.html
Hey @PRIYESHSINGH24 ,
Could you Please review and let me know if any further updates are needed and merge this PR under SWOC. 😊
Screenrecording : 
https://github.com/user-attachments/assets/7113a3a6-b55b-41a3-9644-fd279e29d144
=> Testimonial Page added

Security.html
Fixed @PRIYESHSINGH24 Add SWOC level to this PR 
https://github.com/user-attachments/assets/9b5f65ee-7082-41eb-a740-625cb16f079a
=> improve header and footer in security page

contact.html, pages/Login.html, pages/SignUp.html
solved
issue #617 
I have solved issue for nav link in three pages- sign in, signup and contact
before
https://github.com/user-attachments/assets/0376fd34-1a33-4595-85e7-301c2f0b33d4
after
https://github.com/user-attachments/assets/fda8e710-ef44-4dde-8407-b1bf31fecc5d
=> Solved issues for the nav links

pages/platform.html, pages/scroll.css, pages/scroll.js
Create separate scroll.css and scroll.js files for easier contributions.
look-
=> Fix some bugs and implement smooth scrolling animation on Platforms.html
